// test/widget_test.dart
//
// Basic smoke test updated for GoLongDriveApp (replaces the default
// counter-app test generated by `flutter create`).

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:project/app.dart';

void main() {
  testWidgets('App launches and shows splash screen', (WidgetTester tester) async {
    await tester.pumpWidget(const GoLongDriveApp());

    // Splash screen should be showing right after launch.
    expect(find.byType(Scaffold), findsOneWidget);
    expect(find.text('Your ride, your journey'), findsOneWidget);
  });
}